live_config_reload = true

import = [
    "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Maximized"
title           = "Alacritty"

[window.dimensions]
columns = 0
lines   = 0

[window.padding]
x = 12
y = 12

[scrolling]
history = 12000

[font]
builtin_box_drawing = false
size                = 14

[font.bold]
family = "DroidSansM Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "DroidSansM Nerd Font"
style  = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "DroidSansM Nerd Font"
style  = "Italic"

[font.normal]
family = "DroidSansM Nerd Font"
style  = "Regular"

[font.offset]
x = 0
y = 0

[bell]
animation = "EaseOutExpo"
color     = "#C0C5CE"
command   = "None"
duration  = 0

[selection]
save_to_clipboard     = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
unfocused_hollow = true
vi_mode_style    = "None"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false
