#!/usr/bin/env bash
DEV_DIR=$HOME/dev

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$((cd $DEV_DIR && ls -d *(/)) | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)

# Create a new attached session if tmux is not already running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected -c $DEV_DIR/$selected
    exit 0
fi

# The new session needs to be detached otherwise it will be considered a nested
# session and throw an error
if ! tmux has-session -t=$selected 2> /dev/null; then
    tmux new-session -d -s $selected -c $DEV_DIR/$selected
fi

tmux switch-client -t $selected
