#!/usr/bin/env bash
DEV_DIR=$HOME/dev

get_project_directories() {
    find $DEV_DIR -mindepth 1 -maxdepth 1 -type d
}

get_all() {
    echo scratch
    get_project_directories
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(get_all | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ $selected == scratch ]]; then
    name=scratch
    directory=$PWD
else
    name=$(basename $selected | tr -d .)
    directory=$selected
fi

tmux_running=$(pgrep tmux)

# Create a new attached session if tmux is not already running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $name -c $directory
    exit 0
fi

# The new session needs to be detached otherwise it will be considered a nested
# session and throw an error
if ! tmux has-session -t=$name 2> /dev/null; then
    tmux new-session -d -s $name -c $directory
fi

if [[ -n $TMUX ]]; then
    tmux switch-client -t $name
else
    tmux attach-session -t $name
fi
